// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjpO4rlhVrqZ8A7tj_rOb2vk025ie_OzY',
    appId: '1:568581207106:web:addcd3ce4819c4642169db',
    messagingSenderId: '568581207106',
    projectId: 'typaapp-5e868',
    authDomain: 'typaapp-5e868.firebaseapp.com',
    storageBucket: 'typaapp-5e868.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMUvS1SJ3-EbTnAdIZtAzVtmyJ7vdblU',
    appId: '1:568581207106:android:4d702dd4609c3a892169db',
    messagingSenderId: '568581207106',
    projectId: 'typaapp-5e868',
    storageBucket: 'typaapp-5e868.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkMOyFVyDG8k2xU-dey-ynq65wHO7wuQ',
    appId: '1:568581207106:ios:774386d21089bfe42169db',
    messagingSenderId: '568581207106',
    projectId: 'typaapp-5e868',
    storageBucket: 'typaapp-5e868.firebasestorage.app',
    iosBundleId: 'com.example.typaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFkMOyFVyDG8k2xU-dey-ynq65wHO7wuQ',
    appId: '1:568581207106:ios:774386d21089bfe42169db',
    messagingSenderId: '568581207106',
    projectId: 'typaapp-5e868',
    storageBucket: 'typaapp-5e868.firebasestorage.app',
    iosBundleId: 'com.example.typaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjpO4rlhVrqZ8A7tj_rOb2vk025ie_OzY',
    appId: '1:568581207106:web:a74ca35ddebe459e2169db',
    messagingSenderId: '568581207106',
    projectId: 'typaapp-5e868',
    authDomain: 'typaapp-5e868.firebaseapp.com',
    storageBucket: 'typaapp-5e868.firebasestorage.app',
  );
}
